### ISSUE TITLE
Some problems have incorrect problem number in csv / json.

### ISSUE THREAD

**Issue by PedroNavHur** [adixmr/leetcode#3]
Some problems such as 1719 have the incorrect problem in the csv.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/25333174/229327569-0a42776e-6329-4c7f-9c98-713c1bcb2bb9.png">

Problem 1719 is actually https://leetcode.com/problems/number-of-ways-to-reconstruct-a-tree/

Are you generating the csv / json differently from the google sheets?

**Comment by adixmr** [comment]
You're looking at the wrong id, this id is being used internally by Leetcode. Please have a look at frontend question id column on the right, that's what you're expecting. It'll match with the ID you see on Leetcode UI.

**Comment by PedroNavHur** [comment]
Ohh nice, thank you!
