### ISSUE TITLE
Is the live page still running?

### ISSUE THREAD

**Issue by Akarsh1** [adixmr/leetcode#8]
Hello Aditya,

Thanks for curating the list of leetcode questions according to their respective topics.

I was wondering if the live page is still running? I tried accessing it but I am not able to access it. It shows some errors.

Thanks.

**Comment by adixmr** [comment]
Thanks for bringing this to my notice. The server is up now, please check again.

**Comment by Akarsh1** [comment]
Thanks. The server is running fine now.

**Comment by Akarsh1** [comment]
> Thanks for bringing this to my notice. The server is up now, please check again.

Thanks. The server is running fine now.
